site_name:  tbongiovani-blueprint
site_description:  Lib de referencia para criaçao e utilização de prompts dentro do ecossistema de Loterias - Squad Refatoração

nav:
  - Home: index.md
  - Section 1:
      - Sub Section 1.1: section1/s1.md
      - Sub Section 1.2: section1/s2.md
      - Sub Section 1.3: section1/s3.md

plugins:
  - techdocs-core